### ISSUE TITLE
Wiki merge request - fix dead link

### ISSUE THREAD

**Issue by RoiKlevansky** [ariecattan/biuoop2022#1]
Hey there,
Submission-Instructions.md of the wiki contains a dead link `http://submit.cs.biu.ac.il/` which needs to be changed to `https://submit.cs.biu.ac.il/`.

I have forked the wiki and pushed the change to the [fork](https://github.com/RoiKlevansky/biuoop2022-wiki).
If possible please give it a look and merge it if you'd like.

Thanks and have a good day.

**Comment by ariecattan** [comment]
Thanks! 

(you didn't fork the repo but only created an independent repo so I can't easily accept your pull request. Anyway, I've fixed the issue directly)

**Comment by RoiKlevansky** [comment]
Thank you!
